# Generated by Django 4.2.7 on 2026-01-17 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Manufacturer batch number (e.g., LOT-2024-001)', max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price - printed on product (for display/reference only)', max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=2, help_text='Selling Rate - price at which customer buys (USED FOR BILLING ONLY)', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost Price - purchase price (internal reference only, NOT shown in billing)', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Available quantity for this batch')),
                ('expiry_date', models.DateField(help_text='Expiry date for this batch. Format: YYYY-MM-DD.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('name', models.CharField(help_text="Unique identifier (lowercase, alphanumeric + underscore). E.g., 'tablet', 'gel', 'spray'", max_length=50, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(help_text="Display label. E.g., 'Tablet', 'Gel', 'Spray'", max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='True for built-in types (tablet, syrup, powder, cream, diaper, condom, sachet)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesaler', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial Payment'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial Payment'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_bill', to='inventory.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_type', models.CharField(help_text='Type of product (references ProductType.name). Can be default or custom type.', max_length=50)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(default='pc', help_text='Unit of sale (pc, bottle, gm, ml, etc.) - flexible per product', max_length=50)),
                ('salt_composition', models.CharField(blank=True, help_text="Active salt/composition (optional, mainly for tablets/capsules). E.g., 'Paracetamol 500mg'", max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['product_type'], name='inventory_p_product_3c97c6_idx'), models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Batch number for traceability', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity sold from this batch')),
                ('original_selling_rate', models.DecimalField(decimal_places=2, help_text='Original selling rate from batch (for price history)', max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=2, help_text='Final selling rate (may be edited during billing)', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='MRP for reference/display only (not used in calculations)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'ordering': ['invoice', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='inventory_i_created_b50583_idx'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='inventory_i_invoice_7140b7_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'batch_number'], name='inventory_b_product_09fdd0_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'batch_number')},
        ),
    ]
