# Generated by Django 6.0.1 on 2026-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_hsn_product_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Customer Address', null=True),
        ),
    ]
